### ISSUE TITLE
expose auth token 

### ISSUE THREAD

**Issue by ni30gupta** [telecmi/piopiy_client_js#47]
I have intigrated you telecmi in my company dashboard
made a componnet which mount when slick on start call button
but everytime i have to make login before making call.
there is no way that i can store the token and re use when calling to another person

 // If Login Success, then make the call
    this.piopiy.on('login', (object) => {
      console.log("login ok", object, this.piopiy)
      this.makeCall()
    });
    
    see here neither in call back nor in this.piopy object i am seeing the auth token
    while i can see in network call, there is an api hit , and in response it send the auth token
    but we need it here some how

**Comment by murugancmi** [comment]
@ni30gupta sorry for the late reply please have a look at this example implementation https://github.com/telecmi/react_piopiy_client_js/tree/main hope it will help you

**Comment by murugancmi** [comment]
without any conversation  more then 7 days so closing this issue

**Comment by ni30gupta** [comment]
thanks
